//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVUHMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientVital()
        {
            this.Consultations = new HashSet<Consultation>();
            this.PharmacyPatientPrescriptions = new HashSet<PharmacyPatientPrescription>();
            this.Prescriptions = new HashSet<Prescription>();
        }
    
        public int VitalID { get; set; }
        public string Patient_ID { get; set; }
        public double Temperature { get; set; }
        public double Weight { get; set; }
        public string BloodPressure { get; set; }
        public Nullable<double> SugarLevel { get; set; }
        public string PregnancyTest { get; set; }
        public System.DateTime Date { get; set; }
        public string SeenDoctor { get; set; }
        public string isCheckUp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> Consultations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PharmacyPatientPrescription> PharmacyPatientPrescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescriptions { get; set; }
    }
}
