//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VVUHMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VVUHMSEntities : DbContext
    {
        public VVUHMSEntities()
            : base("name=VVUHMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultation> Consultations { get; set; }
        public virtual DbSet<Drug> Drugs { get; set; }
        public virtual DbSet<ForwardRecord> ForwardRecords { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientVital> PatientVitals { get; set; }
        public virtual DbSet<PharmacyPatientPrescription> PharmacyPatientPrescriptions { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
