namespace VVUHMS.Forms.UserControls
{
    partial class AddRecordPage
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddRecordPage));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.AddRecordPanel = new System.Windows.Forms.Panel();
            this.btnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.txtDOB = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.ddSex = new Bunifu.UI.WinForms.BunifuDropdown();
            this.txtLName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtOName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtFName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtNHIS = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtOccupation = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtDisease = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtAddress = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtSPhone = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txtPPhone = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.AddRecordPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuLabel1.Font = new System.Drawing.Font("Microsoft YaHei", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(179)))), ((int)(((byte)(60)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(845, 55);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Add Records";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // AddRecordPanel
            // 
            this.AddRecordPanel.Controls.Add(this.btnAdd);
            this.AddRecordPanel.Controls.Add(this.splitContainer1);
            this.AddRecordPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AddRecordPanel.Location = new System.Drawing.Point(0, 55);
            this.AddRecordPanel.Name = "AddRecordPanel";
            this.AddRecordPanel.Size = new System.Drawing.Size(845, 455);
            this.AddRecordPanel.TabIndex = 2;
            // 
            // btnAdd
            // 
            this.btnAdd.AllowToggling = false;
            this.btnAdd.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btnAdd.AnimationSpeed = 200;
            this.btnAdd.AutoGenerateColors = false;
            this.btnAdd.BackColor = System.Drawing.Color.Transparent;
            this.btnAdd.BackColor1 = System.Drawing.Color.Transparent;
            this.btnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.BackgroundImage")));
            this.btnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.ButtonText = "Add Record";
            this.btnAdd.ButtonTextMarginLeft = 0;
            this.btnAdd.ColorContrastOnClick = 45;
            this.btnAdd.ColorContrastOnHover = 45;
            this.btnAdd.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAdd.CustomizableEdges = borderEdges1;
            this.btnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAdd.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.btnAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.btnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAdd.IconMarginLeft = 11;
            this.btnAdd.IconPadding = 10;
            this.btnAdd.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnAdd.IdleBorderColor = System.Drawing.Color.LightGray;
            this.btnAdd.IdleBorderRadius = 3;
            this.btnAdd.IdleBorderThickness = 1;
            this.btnAdd.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnAdd.IdleIconLeftImage = null;
            this.btnAdd.IdleIconRightImage = null;
            this.btnAdd.IndicateFocus = false;
            this.btnAdd.Location = new System.Drawing.Point(225, 378);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.btnAdd.onHoverState.BorderRadius = 3;
            this.btnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.onHoverState.BorderThickness = 1;
            this.btnAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.btnAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.onHoverState.IconLeftImage = null;
            this.btnAdd.onHoverState.IconRightImage = null;
            this.btnAdd.OnIdleState.BorderColor = System.Drawing.Color.LightGray;
            this.btnAdd.OnIdleState.BorderRadius = 3;
            this.btnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnIdleState.BorderThickness = 1;
            this.btnAdd.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.btnAdd.OnIdleState.IconLeftImage = null;
            this.btnAdd.OnIdleState.IconRightImage = null;
            this.btnAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(8)))), ((int)(((byte)(111)))));
            this.btnAdd.OnPressedState.BorderRadius = 3;
            this.btnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnPressedState.BorderThickness = 1;
            this.btnAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(49)))), ((int)(((byte)(8)))), ((int)(((byte)(111)))));
            this.btnAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnPressedState.IconLeftImage = null;
            this.btnAdd.OnPressedState.IconRightImage = null;
            this.btnAdd.Size = new System.Drawing.Size(396, 45);
            this.btnAdd.TabIndex = 1;
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAdd.TextMarginLeft = 0;
            this.btnAdd.UseDefaultRadiusAndThickness = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Top;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.txtDOB);
            this.splitContainer1.Panel1.Controls.Add(this.ddSex);
            this.splitContainer1.Panel1.Controls.Add(this.txtLName);
            this.splitContainer1.Panel1.Controls.Add(this.txtOName);
            this.splitContainer1.Panel1.Controls.Add(this.txtEmail);
            this.splitContainer1.Panel1.Controls.Add(this.txtFName);
            this.splitContainer1.Panel1.Controls.Add(this.txtNHIS);
            this.splitContainer1.Panel1.Padding = new System.Windows.Forms.Padding(20);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.txtOccupation);
            this.splitContainer1.Panel2.Controls.Add(this.txtDisease);
            this.splitContainer1.Panel2.Controls.Add(this.txtAddress);
            this.splitContainer1.Panel2.Controls.Add(this.txtSPhone);
            this.splitContainer1.Panel2.Controls.Add(this.txtPPhone);
            this.splitContainer1.Panel2.Padding = new System.Windows.Forms.Padding(20);
            this.splitContainer1.Size = new System.Drawing.Size(845, 354);
            this.splitContainer1.SplitterDistance = 424;
            this.splitContainer1.TabIndex = 0;
            // 
            // txtDOB
            // 
            this.txtDOB.BorderRadius = 1;
            this.txtDOB.Color = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtDOB.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thick;
            this.txtDOB.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.txtDOB.DisabledColor = System.Drawing.Color.Gray;
            this.txtDOB.DisplayWeekNumbers = false;
            this.txtDOB.DPHeight = 0;
            this.txtDOB.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.txtDOB.FillDatePicker = false;
            this.txtDOB.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtDOB.Icon = ((System.Drawing.Image)(resources.GetObject("txtDOB.Icon")));
            this.txtDOB.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtDOB.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.txtDOB.Location = new System.Drawing.Point(184, 228);
            this.txtDOB.MinimumSize = new System.Drawing.Size(217, 32);
            this.txtDOB.Name = "txtDOB";
            this.txtDOB.Size = new System.Drawing.Size(217, 32);
            this.txtDOB.TabIndex = 5;
            // 
            // ddSex
            // 
            this.ddSex.BackColor = System.Drawing.Color.White;
            this.ddSex.BorderRadius = 1;
            this.ddSex.Color = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.ddSex.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.ddSex.DisabledColor = System.Drawing.Color.Gray;
            this.ddSex.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.ddSex.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thick;
            this.ddSex.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.ddSex.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.ddSex.FillDropDown = false;
            this.ddSex.FillIndicator = false;
            this.ddSex.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.ddSex.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.ddSex.FormattingEnabled = true;
            this.ddSex.Icon = null;
            this.ddSex.IndicatorColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.ddSex.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.ddSex.ItemBackColor = System.Drawing.Color.White;
            this.ddSex.ItemBorderColor = System.Drawing.Color.White;
            this.ddSex.ItemForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.ddSex.ItemHeight = 26;
            this.ddSex.ItemHighLightColor = System.Drawing.Color.Thistle;
            this.ddSex.Items.AddRange(new object[] {
            "Male",
            "Female"});
            this.ddSex.Location = new System.Drawing.Point(20, 228);
            this.ddSex.Name = "ddSex";
            this.ddSex.Size = new System.Drawing.Size(157, 32);
            this.ddSex.TabIndex = 4;
            this.ddSex.Text = null;
            // 
            // txtLName
            // 
            this.txtLName.AcceptsReturn = false;
            this.txtLName.AcceptsTab = false;
            this.txtLName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtLName.AnimationSpeed = 200;
            this.txtLName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLName.BackColor = System.Drawing.Color.White;
            this.txtLName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLName.BackgroundImage")));
            this.txtLName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtLName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtLName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtLName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtLName.BorderRadius = 1;
            this.txtLName.BorderThickness = 1;
            this.txtLName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtLName.DefaultText = "";
            this.txtLName.FillColor = System.Drawing.Color.White;
            this.txtLName.HideSelection = true;
            this.txtLName.IconLeft = null;
            this.txtLName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLName.IconPadding = 10;
            this.txtLName.IconRight = null;
            this.txtLName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLName.Lines = new string[0];
            this.txtLName.Location = new System.Drawing.Point(20, 176);
            this.txtLName.MaxLength = 32767;
            this.txtLName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLName.Modified = false;
            this.txtLName.Multiline = false;
            this.txtLName.Name = "txtLName";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLName.OnIdleState = stateProperties4;
            this.txtLName.PasswordChar = '\0';
            this.txtLName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLName.PlaceholderText = "Last Name";
            this.txtLName.ReadOnly = false;
            this.txtLName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLName.SelectedText = "";
            this.txtLName.SelectionLength = 0;
            this.txtLName.SelectionStart = 0;
            this.txtLName.ShortcutsEnabled = true;
            this.txtLName.Size = new System.Drawing.Size(384, 31);
            this.txtLName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtLName.TabIndex = 3;
            this.txtLName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLName.TextMarginBottom = 0;
            this.txtLName.TextMarginLeft = 5;
            this.txtLName.TextMarginTop = 0;
            this.txtLName.TextPlaceholder = "Last Name";
            this.txtLName.UseSystemPasswordChar = false;
            this.txtLName.WordWrap = true;
            // 
            // txtOName
            // 
            this.txtOName.AcceptsReturn = false;
            this.txtOName.AcceptsTab = false;
            this.txtOName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtOName.AnimationSpeed = 200;
            this.txtOName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtOName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtOName.BackColor = System.Drawing.Color.White;
            this.txtOName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtOName.BackgroundImage")));
            this.txtOName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtOName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtOName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtOName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtOName.BorderRadius = 1;
            this.txtOName.BorderThickness = 1;
            this.txtOName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtOName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtOName.DefaultText = "";
            this.txtOName.FillColor = System.Drawing.Color.White;
            this.txtOName.HideSelection = true;
            this.txtOName.IconLeft = null;
            this.txtOName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOName.IconPadding = 10;
            this.txtOName.IconRight = null;
            this.txtOName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOName.Lines = new string[0];
            this.txtOName.Location = new System.Drawing.Point(20, 124);
            this.txtOName.MaxLength = 32767;
            this.txtOName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtOName.Modified = false;
            this.txtOName.Multiline = false;
            this.txtOName.Name = "txtOName";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtOName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOName.OnIdleState = stateProperties8;
            this.txtOName.PasswordChar = '\0';
            this.txtOName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtOName.PlaceholderText = "Other Names";
            this.txtOName.ReadOnly = false;
            this.txtOName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtOName.SelectedText = "";
            this.txtOName.SelectionLength = 0;
            this.txtOName.SelectionStart = 0;
            this.txtOName.ShortcutsEnabled = true;
            this.txtOName.Size = new System.Drawing.Size(384, 31);
            this.txtOName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtOName.TabIndex = 2;
            this.txtOName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtOName.TextMarginBottom = 0;
            this.txtOName.TextMarginLeft = 5;
            this.txtOName.TextMarginTop = 0;
            this.txtOName.TextPlaceholder = "Other Names";
            this.txtOName.UseSystemPasswordChar = false;
            this.txtOName.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.White;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(20, 280);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties12;
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "Email Address";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(384, 31);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtEmail.TabIndex = 6;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 5;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "Email Address";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // txtFName
            // 
            this.txtFName.AcceptsReturn = false;
            this.txtFName.AcceptsTab = false;
            this.txtFName.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtFName.AnimationSpeed = 200;
            this.txtFName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFName.BackColor = System.Drawing.Color.White;
            this.txtFName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFName.BackgroundImage")));
            this.txtFName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtFName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtFName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtFName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtFName.BorderRadius = 1;
            this.txtFName.BorderThickness = 1;
            this.txtFName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtFName.DefaultText = "";
            this.txtFName.FillColor = System.Drawing.Color.White;
            this.txtFName.HideSelection = true;
            this.txtFName.IconLeft = null;
            this.txtFName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFName.IconPadding = 10;
            this.txtFName.IconRight = null;
            this.txtFName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFName.Lines = new string[0];
            this.txtFName.Location = new System.Drawing.Point(20, 72);
            this.txtFName.MaxLength = 32767;
            this.txtFName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFName.Modified = false;
            this.txtFName.Multiline = false;
            this.txtFName.Name = "txtFName";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFName.OnIdleState = stateProperties16;
            this.txtFName.PasswordChar = '\0';
            this.txtFName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFName.PlaceholderText = "First Name";
            this.txtFName.ReadOnly = false;
            this.txtFName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFName.SelectedText = "";
            this.txtFName.SelectionLength = 0;
            this.txtFName.SelectionStart = 0;
            this.txtFName.ShortcutsEnabled = true;
            this.txtFName.Size = new System.Drawing.Size(384, 31);
            this.txtFName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtFName.TabIndex = 1;
            this.txtFName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFName.TextMarginBottom = 0;
            this.txtFName.TextMarginLeft = 5;
            this.txtFName.TextMarginTop = 0;
            this.txtFName.TextPlaceholder = "First Name";
            this.txtFName.UseSystemPasswordChar = false;
            this.txtFName.WordWrap = true;
            // 
            // txtNHIS
            // 
            this.txtNHIS.AcceptsReturn = false;
            this.txtNHIS.AcceptsTab = false;
            this.txtNHIS.AnimationSpeed = 200;
            this.txtNHIS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNHIS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNHIS.BackColor = System.Drawing.Color.White;
            this.txtNHIS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNHIS.BackgroundImage")));
            this.txtNHIS.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtNHIS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtNHIS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtNHIS.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNHIS.BorderRadius = 1;
            this.txtNHIS.BorderThickness = 1;
            this.txtNHIS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNHIS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNHIS.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtNHIS.DefaultText = "";
            this.txtNHIS.Dock = System.Windows.Forms.DockStyle.Top;
            this.txtNHIS.FillColor = System.Drawing.Color.White;
            this.txtNHIS.HideSelection = true;
            this.txtNHIS.IconLeft = null;
            this.txtNHIS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNHIS.IconPadding = 10;
            this.txtNHIS.IconRight = null;
            this.txtNHIS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNHIS.Lines = new string[0];
            this.txtNHIS.Location = new System.Drawing.Point(20, 20);
            this.txtNHIS.MaxLength = 32767;
            this.txtNHIS.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNHIS.Modified = false;
            this.txtNHIS.Multiline = false;
            this.txtNHIS.Name = "txtNHIS";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNHIS.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNHIS.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNHIS.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNHIS.OnIdleState = stateProperties20;
            this.txtNHIS.PasswordChar = '\0';
            this.txtNHIS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNHIS.PlaceholderText = "NHIS ID";
            this.txtNHIS.ReadOnly = false;
            this.txtNHIS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNHIS.SelectedText = "";
            this.txtNHIS.SelectionLength = 0;
            this.txtNHIS.SelectionStart = 0;
            this.txtNHIS.ShortcutsEnabled = true;
            this.txtNHIS.Size = new System.Drawing.Size(384, 31);
            this.txtNHIS.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtNHIS.TabIndex = 0;
            this.txtNHIS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNHIS.TextMarginBottom = 0;
            this.txtNHIS.TextMarginLeft = 5;
            this.txtNHIS.TextMarginTop = 0;
            this.txtNHIS.TextPlaceholder = "NHIS ID";
            this.txtNHIS.UseSystemPasswordChar = false;
            this.txtNHIS.WordWrap = true;
            // 
            // txtOccupation
            // 
            this.txtOccupation.AcceptsReturn = false;
            this.txtOccupation.AcceptsTab = false;
            this.txtOccupation.AnimationSpeed = 200;
            this.txtOccupation.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtOccupation.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtOccupation.BackColor = System.Drawing.Color.White;
            this.txtOccupation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtOccupation.BackgroundImage")));
            this.txtOccupation.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtOccupation.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtOccupation.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtOccupation.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtOccupation.BorderRadius = 1;
            this.txtOccupation.BorderThickness = 1;
            this.txtOccupation.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtOccupation.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOccupation.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txtOccupation.DefaultText = "";
            this.txtOccupation.FillColor = System.Drawing.Color.White;
            this.txtOccupation.HideSelection = true;
            this.txtOccupation.IconLeft = null;
            this.txtOccupation.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOccupation.IconPadding = 10;
            this.txtOccupation.IconRight = null;
            this.txtOccupation.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOccupation.Lines = new string[0];
            this.txtOccupation.Location = new System.Drawing.Point(21, 228);
            this.txtOccupation.MaxLength = 32767;
            this.txtOccupation.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtOccupation.Modified = false;
            this.txtOccupation.Multiline = false;
            this.txtOccupation.Name = "txtOccupation";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOccupation.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtOccupation.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOccupation.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOccupation.OnIdleState = stateProperties24;
            this.txtOccupation.PasswordChar = '\0';
            this.txtOccupation.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtOccupation.PlaceholderText = "Occupation";
            this.txtOccupation.ReadOnly = false;
            this.txtOccupation.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtOccupation.SelectedText = "";
            this.txtOccupation.SelectionLength = 0;
            this.txtOccupation.SelectionStart = 0;
            this.txtOccupation.ShortcutsEnabled = true;
            this.txtOccupation.Size = new System.Drawing.Size(373, 29);
            this.txtOccupation.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtOccupation.TabIndex = 4;
            this.txtOccupation.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtOccupation.TextMarginBottom = 0;
            this.txtOccupation.TextMarginLeft = 5;
            this.txtOccupation.TextMarginTop = 0;
            this.txtOccupation.TextPlaceholder = "Occupation";
            this.txtOccupation.UseSystemPasswordChar = false;
            this.txtOccupation.WordWrap = true;
            // 
            // txtDisease
            // 
            this.txtDisease.AcceptsReturn = false;
            this.txtDisease.AcceptsTab = false;
            this.txtDisease.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtDisease.AnimationSpeed = 200;
            this.txtDisease.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDisease.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDisease.BackColor = System.Drawing.Color.White;
            this.txtDisease.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDisease.BackgroundImage")));
            this.txtDisease.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtDisease.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtDisease.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtDisease.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDisease.BorderRadius = 1;
            this.txtDisease.BorderThickness = 1;
            this.txtDisease.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDisease.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDisease.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtDisease.DefaultText = "";
            this.txtDisease.FillColor = System.Drawing.Color.White;
            this.txtDisease.HideSelection = true;
            this.txtDisease.IconLeft = null;
            this.txtDisease.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDisease.IconPadding = 10;
            this.txtDisease.IconRight = null;
            this.txtDisease.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDisease.Lines = new string[0];
            this.txtDisease.Location = new System.Drawing.Point(21, 72);
            this.txtDisease.MaxLength = 32767;
            this.txtDisease.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDisease.Modified = false;
            this.txtDisease.Multiline = false;
            this.txtDisease.Name = "txtDisease";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDisease.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDisease.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDisease.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDisease.OnIdleState = stateProperties28;
            this.txtDisease.PasswordChar = '\0';
            this.txtDisease.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDisease.PlaceholderText = "Terminal or Lifetime Illness";
            this.txtDisease.ReadOnly = false;
            this.txtDisease.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDisease.SelectedText = "";
            this.txtDisease.SelectionLength = 0;
            this.txtDisease.SelectionStart = 0;
            this.txtDisease.ShortcutsEnabled = true;
            this.txtDisease.Size = new System.Drawing.Size(373, 31);
            this.txtDisease.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtDisease.TabIndex = 1;
            this.txtDisease.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDisease.TextMarginBottom = 0;
            this.txtDisease.TextMarginLeft = 5;
            this.txtDisease.TextMarginTop = 0;
            this.txtDisease.TextPlaceholder = "Terminal or Lifetime Illness";
            this.txtDisease.UseSystemPasswordChar = false;
            this.txtDisease.WordWrap = true;
            // 
            // txtAddress
            // 
            this.txtAddress.AcceptsReturn = false;
            this.txtAddress.AcceptsTab = false;
            this.txtAddress.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtAddress.AnimationSpeed = 200;
            this.txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddress.BackColor = System.Drawing.Color.White;
            this.txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddress.BackgroundImage")));
            this.txtAddress.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAddress.BorderRadius = 1;
            this.txtAddress.BorderThickness = 1;
            this.txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtAddress.DefaultText = "";
            this.txtAddress.FillColor = System.Drawing.Color.White;
            this.txtAddress.HideSelection = true;
            this.txtAddress.IconLeft = null;
            this.txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.IconPadding = 10;
            this.txtAddress.IconRight = null;
            this.txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.Lines = new string[0];
            this.txtAddress.Location = new System.Drawing.Point(21, 20);
            this.txtAddress.MaxLength = 32767;
            this.txtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAddress.Modified = false;
            this.txtAddress.Multiline = false;
            this.txtAddress.Name = "txtAddress";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Empty;
            stateProperties30.FillColor = System.Drawing.Color.White;
            stateProperties30.ForeColor = System.Drawing.Color.Empty;
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnIdleState = stateProperties32;
            this.txtAddress.PasswordChar = '\0';
            this.txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.PlaceholderText = "Residential Address";
            this.txtAddress.ReadOnly = false;
            this.txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddress.SelectedText = "";
            this.txtAddress.SelectionLength = 0;
            this.txtAddress.SelectionStart = 0;
            this.txtAddress.ShortcutsEnabled = true;
            this.txtAddress.Size = new System.Drawing.Size(373, 31);
            this.txtAddress.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtAddress.TabIndex = 0;
            this.txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddress.TextMarginBottom = 0;
            this.txtAddress.TextMarginLeft = 5;
            this.txtAddress.TextMarginTop = 0;
            this.txtAddress.TextPlaceholder = "Residential Address";
            this.txtAddress.UseSystemPasswordChar = false;
            this.txtAddress.WordWrap = true;
            // 
            // txtSPhone
            // 
            this.txtSPhone.AcceptsReturn = false;
            this.txtSPhone.AcceptsTab = false;
            this.txtSPhone.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtSPhone.AnimationSpeed = 200;
            this.txtSPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSPhone.BackColor = System.Drawing.Color.White;
            this.txtSPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSPhone.BackgroundImage")));
            this.txtSPhone.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtSPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtSPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtSPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSPhone.BorderRadius = 1;
            this.txtSPhone.BorderThickness = 1;
            this.txtSPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSPhone.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtSPhone.DefaultText = "";
            this.txtSPhone.FillColor = System.Drawing.Color.White;
            this.txtSPhone.HideSelection = true;
            this.txtSPhone.IconLeft = null;
            this.txtSPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSPhone.IconPadding = 10;
            this.txtSPhone.IconRight = null;
            this.txtSPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSPhone.Lines = new string[0];
            this.txtSPhone.Location = new System.Drawing.Point(21, 176);
            this.txtSPhone.MaxLength = 32767;
            this.txtSPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSPhone.Modified = false;
            this.txtSPhone.Multiline = false;
            this.txtSPhone.Name = "txtSPhone";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSPhone.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Empty;
            stateProperties34.FillColor = System.Drawing.Color.White;
            stateProperties34.ForeColor = System.Drawing.Color.Empty;
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSPhone.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSPhone.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSPhone.OnIdleState = stateProperties36;
            this.txtSPhone.PasswordChar = '\0';
            this.txtSPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSPhone.PlaceholderText = "Secondary Phone Number";
            this.txtSPhone.ReadOnly = false;
            this.txtSPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSPhone.SelectedText = "";
            this.txtSPhone.SelectionLength = 0;
            this.txtSPhone.SelectionStart = 0;
            this.txtSPhone.ShortcutsEnabled = true;
            this.txtSPhone.Size = new System.Drawing.Size(373, 31);
            this.txtSPhone.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtSPhone.TabIndex = 3;
            this.txtSPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSPhone.TextMarginBottom = 0;
            this.txtSPhone.TextMarginLeft = 5;
            this.txtSPhone.TextMarginTop = 0;
            this.txtSPhone.TextPlaceholder = "Secondary Phone Number";
            this.txtSPhone.UseSystemPasswordChar = false;
            this.txtSPhone.WordWrap = true;
            // 
            // txtPPhone
            // 
            this.txtPPhone.AcceptsReturn = false;
            this.txtPPhone.AcceptsTab = false;
            this.txtPPhone.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtPPhone.AnimationSpeed = 200;
            this.txtPPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPPhone.BackColor = System.Drawing.Color.White;
            this.txtPPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPPhone.BackgroundImage")));
            this.txtPPhone.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            this.txtPPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txtPPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            this.txtPPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPPhone.BorderRadius = 1;
            this.txtPPhone.BorderThickness = 1;
            this.txtPPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPPhone.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 11F);
            this.txtPPhone.DefaultText = "";
            this.txtPPhone.FillColor = System.Drawing.Color.White;
            this.txtPPhone.HideSelection = true;
            this.txtPPhone.IconLeft = null;
            this.txtPPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPPhone.IconPadding = 10;
            this.txtPPhone.IconRight = null;
            this.txtPPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPPhone.Lines = new string[0];
            this.txtPPhone.Location = new System.Drawing.Point(21, 124);
            this.txtPPhone.MaxLength = 32767;
            this.txtPPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPPhone.Modified = false;
            this.txtPPhone.Multiline = false;
            this.txtPPhone.Name = "txtPPhone";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(14)))), ((int)(((byte)(111)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPPhone.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Empty;
            stateProperties38.FillColor = System.Drawing.Color.White;
            stateProperties38.ForeColor = System.Drawing.Color.Empty;
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPPhone.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(119)))), ((int)(((byte)(157)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPPhone.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPPhone.OnIdleState = stateProperties40;
            this.txtPPhone.PasswordChar = '\0';
            this.txtPPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPPhone.PlaceholderText = "Primary Phone Number";
            this.txtPPhone.ReadOnly = false;
            this.txtPPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPPhone.SelectedText = "";
            this.txtPPhone.SelectionLength = 0;
            this.txtPPhone.SelectionStart = 0;
            this.txtPPhone.ShortcutsEnabled = true;
            this.txtPPhone.Size = new System.Drawing.Size(373, 31);
            this.txtPPhone.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Material;
            this.txtPPhone.TabIndex = 2;
            this.txtPPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPPhone.TextMarginBottom = 0;
            this.txtPPhone.TextMarginLeft = 5;
            this.txtPPhone.TextMarginTop = 0;
            this.txtPPhone.TextPlaceholder = "Primary Phone Number";
            this.txtPPhone.UseSystemPasswordChar = false;
            this.txtPPhone.WordWrap = true;
            // 
            // AddRecordPage
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.AddRecordPanel);
            this.Controls.Add(this.bunifuLabel1);
            this.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "AddRecordPage";
            this.Size = new System.Drawing.Size(845, 510);
            this.AddRecordPanel.ResumeLayout(false);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private System.Windows.Forms.Panel AddRecordPanel;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtLName;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtOName;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtFName;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtNHIS;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtSPhone;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtPPhone;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAdd;
        private Bunifu.UI.WinForms.BunifuDatePicker txtDOB;
        private Bunifu.UI.WinForms.BunifuDropdown ddSex;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtDisease;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtAddress;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txtOccupation;
    }
}
